### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by rustervan** [Exatek-Germany/CPUAffinityGameBooster#6]
Hello! Can you check that when you want to download directly it is stopped by a malware warning?:;
wacatac.b!ml

**Comment by tall1on** [comment]
Which Browser are you using to download? Chrome works fine for me.

Sadly we have some false positives as you can see on Virustotal: https://www.virustotal.com/gui/file/e3f4f8b3e26cb119c7bc586cc33a6f5e5b2342bf1b9b9953978e4ebfd1f7fc0f

**Comment by tall1on** [comment]
Small update: i contacted some of the false positive antivirus vendors and hope they resolve the detection. 

Maybe this will also help with getting it fixed for google.

**Comment by tall1on** [comment]
Small update: Microsoft has removed the detection.

**Comment by rustervan** [comment]
Hi! Thank you very much for all the quick management, now I don't send any warning.
