### ISSUE TITLE
new game: Call of Duty®: Modern Warfare® III support

### ISSUE THREAD

**Issue by Apig-Sharbo** [Exatek-Germany/CPUAffinityGameBooster#7]
Hey, great project!

From the supported games list i see `Call of Duty®: Modern Warfare® II`, but not the latest `Call of Duty®: Modern Warfare® III`. While checking i found that it was not applying any affinity, is that something that could be added?

**Comment by tall1on** [comment]
Fixed in master now. I will release a new build shortly. 

Apparently the Discord games API is a bit inaccurate when dealing with the cod.exe when a new "DLC game" like MW3 is released.
